<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>808e93a4-7f26-4694-a226-30357d3121d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-page']/div/div/div/div/form/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.px-4.w-100.text-uppercase.btn.btn-dark-green</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffbadbb0-d495-48b7-ae0d-74be318ea292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 w-100 text-uppercase btn btn-dark-green</value>
      <webElementGuid>e8099b0b-297a-4416-afe7-f7c728aacd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>51397e6f-c1ae-4ea7-b022-51ecce421d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-page&quot;)/div[@class=&quot;justify-content-center row&quot;]/div[@class=&quot;col-12 col-sm-8 col-lg-4&quot;]/div[@class=&quot;p-4 card&quot;]/div[@class=&quot;p-0 card-body&quot;]/form[1]/button[@class=&quot;px-4 w-100 text-uppercase btn btn-dark-green&quot;]</value>
      <webElementGuid>b76d0cdd-ab37-464f-9f1a-25440a498b3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-page']/div/div/div/div/form/button</value>
      <webElementGuid>2bc4133b-e88d-4afa-b70f-42823981e688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login dengan SSO'])[1]/preceding::button[1]</value>
      <webElementGuid>6022fe94-65be-45bd-86ba-6c81529ab566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>96f31dd8-1ec8-4e27-be76-5ae933d3d0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>1e34df8d-12b8-4f8f-ab92-eafa7fa683ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>02976c47-fc73-4cec-a658-e7c9f636c366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
