<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inventory Management System (v 1.1.2)Lo_449022</name>
   <tag></tag>
   <elementGuidId>c1fb5498-d2a3-4fcb-b42b-4537643c1254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.justify-content-center.row</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-page']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c76c1044-33b2-4f74-ba44-007fa433a3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>justify-content-center row</value>
      <webElementGuid>8bb1c2bc-156d-46d4-8441-fa6902b9eb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inventory Management System (v 1.1.2)LoginLogin dengan SSO</value>
      <webElementGuid>52a53c84-2ef9-4ff9-868d-2880822aacd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-page&quot;)/div[@class=&quot;justify-content-center row&quot;]</value>
      <webElementGuid>0eb2ecbd-69d8-4177-869f-c5392ef8fa1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-page']/div</value>
      <webElementGuid>2c3854bb-46f3-4c49-9f6e-95cca2599a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>80caa048-6505-4c07-882f-52d8d065cc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Inventory Management System (v 1.1.2)LoginLogin dengan SSO' or . = 'Inventory Management System (v 1.1.2)LoginLogin dengan SSO')]</value>
      <webElementGuid>fa60f7dc-834d-49be-9a3a-dcb02a6621ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
