<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Inventory Management System</name>
   <tag></tag>
   <elementGuidId>2845fff3-15be-480e-98dc-242221cab127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/header/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.m-0.d-none.d-lg-block.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>96e56753-766c-4a22-be5b-5e01b3767643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 d-none d-lg-block text-white</value>
      <webElementGuid>0559beaa-114c-425c-80b5-e2d8018fb7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inventory Management System</value>
      <webElementGuid>6276cad1-475d-4abf-9fcd-c43343226d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/header[@class=&quot;header-bg-dark-green border-bottom-0 app-header navbar&quot;]/h4[@class=&quot;m-0 d-none d-lg-block text-white&quot;]</value>
      <webElementGuid>395b8f70-5939-45d9-bd98-7b692695a595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/header/h4</value>
      <webElementGuid>51f4a03d-3e91-4da0-ab44-9e06bcdf6097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Password'])[1]/preceding::h4[1]</value>
      <webElementGuid>be5a7c0e-b5bb-4b10-a8e7-68fd5010c6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inventory Management System']/parent::*</value>
      <webElementGuid>0279e011-a599-4b5c-b9cd-4d788764742f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>a77ecdc7-6c9f-435d-8705-76d105e2d60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Inventory Management System' or . = 'Inventory Management System')]</value>
      <webElementGuid>ca8f3c01-7b67-4c6e-b0b2-6685de3236e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
