<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Inventory</name>
   <tag></tag>
   <elementGuidId>ef1136ce-ab62-446d-b6b1-450b21881eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active.breadcrumb-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/main/div/nav/ol/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7a69f13c-8f44-44e8-8264-0c70bb81dce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active breadcrumb-item</value>
      <webElementGuid>4391ff5b-7251-426b-9f92-cd94f1cdffdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>28028c29-9764-4131-b58b-97a46d55ca7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inventory</value>
      <webElementGuid>c2091d86-3a57-408b-ab71-e22535da2320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[1]/nav[1]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;active breadcrumb-item&quot;]</value>
      <webElementGuid>a698ec1b-10de-4dc6-a4ee-54416f80b6d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/main/div/nav/ol/li[2]</value>
      <webElementGuid>a8ad2d6f-e12d-44f0-a924-9d0fdf02ff18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::li[1]</value>
      <webElementGuid>a4711141-4f5d-4ba6-b633-92ce490b3b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Label'])[1]/following::li[2]</value>
      <webElementGuid>547e981c-23f8-4709-ba39-e08d1888067f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Kredit'])[1]/preceding::li[1]</value>
      <webElementGuid>f1ded97e-aa72-44ce-ae77-bfc8a9a9ef39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Kontrak'])[1]/preceding::li[1]</value>
      <webElementGuid>939664cf-012c-4cde-8937-c1520a4dd68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]</value>
      <webElementGuid>40d7629f-ed88-40b3-9173-c6d8582ebb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Inventory' or . = 'Inventory')]</value>
      <webElementGuid>68ed5f1b-1c72-4d60-bda0-eb8f46f47a50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
